fix: avoid a same name of library "random"
from random import SystemRandom -> AttributeError: partially initialized module 'pandas' has no attribute 'DataFrame' (most likely due to a circular import)

caused by a file named "random.py"